### ISSUE TITLE
Issue with Libav (compilation of pictures to create a video). 

### ISSUE THREAD

**Issue by CReis93** [marjoleinbruijning/trackdem#15]
Dear Marjolein,

First of all, a big thank you for developing this script that allows us to analyse the behaviour of our daphnids. The code works perfectly and the tracking is impeccable. 

However, we have some problems when we want to create the tracking video using libav. This is strange, because it worked for a while. But for the last 3 days, it is impossible to make these videos.

The plot(type="animation"....) command does create the temporary file with all the frames, but it seems that libav is not doing its job. Do you have any knowledge of this problem and/or do you have any idea how to fix it?

You'll find a copy of my code on my GitHub : https://github.com/CReis93/DaphnieTracking/blob/main/script

Thanks in advance for your help.

Best regards, 
Christophe

**Comment by marjoleinbruijning** [comment]
Hi Christophe,

Thanks for your message, I'm glad the package is helpful!
I'll be out of office for the next months, so I can't look at the issue in
great detail right now. But you can probably create a workaround by
creating the animation in an alternative way, without libav. See
https://r-graph-gallery.com/166-basic-animated-graph-with-imagemagick.html
for an example that uses Image Magick (you can use trackdem code to create
the png images, and then call image magick to create the animation).
I hope this helps!

Marjolein

Op do 3 nov. 2022 om 16:59 schreef CReis93 ***@***.***>:

**Comment by CReis93** [comment]
Hi Marjolein,

Sorry for the delay, I was also very busy. I found the problem. It was a syntax problem.... Sometimes you look too far! 

Thanks again and all the best. 
Christophe

PS : I close this issue.
