### ISSUE TITLE
loadImages

### ISSUE THREAD

**Issue by NahlaMetwally** [marjoleinbruijning/trackdem#4]
Hello everybody,
I am trying to use trackdem for the first time. I have png sequences. So I tried to load them on r using loadimage function. but I am having this error. If you could help me, will be great thanks in advance.

dir.exists ("/Nahla BNI/R projects/Trackdem/track/1")
dir <- ("/Nahla BNI/R projects/Trackdem/track/1")
allFullImages <- loadImages (dirPictures=dir,nImages=1:30, xranges = NULL,
                             yranges = NULL)

> dir.exists ("/Nahla BNI/R projects/Trackdem/track/1")
[1] TRUE
> dir <- ("/Nahla BNI/R projects/Trackdem/track/1")
> allFullImages <- loadImages (dirPictures=dir,nImages=1:30, xranges = NULL,  yranges = NULL)
Error in im1[yranges, xranges, ] : incorrect number of dimensions

**Comment by marjoleinbruijning** [comment]
Hi Nahla,

are there other files in 'dir' in addition to the .png files? In that case, move those files to make sure that the directory only contains the image sequence.

Best, Marjolein

**Comment by NahlaMetwally** [comment]
Hi Marjolein,
Thanks a lot for the Tip it worked. Now The next problem is that I have already  images' sequence (grey colour) (png extension) so I do not have to convert my videos to images. But I have received this error.
Is there is any way to skip this ??

**Error in createBackground(allFullImages, method = "mean") : 
  Input does not appear to be of the class "TrDm"**

Thanks in advance,
Nahla

**Comment by marjoleinbruijning** [comment]
Hi Nahla,

you can manually change the class of you object using:
class(object) <- c(class(object),'TrDm')

However, in its current release, trackdem only manages color images. I will adapt trackdem to solve this in the next version, likely in the next 2 weeks.
If you want, you can also email me a test sequence (~20-30 images), and I will send you code that should work with these grey color images, 

Best, Marjolein

**Comment by marjoleinbruijning** [comment]
The newest trackdem release (0.4.2) can now also handle greyscale images.
