### ISSUE TITLE
no output on createImageSeq

### ISSUE THREAD

**Issue by pcolangeli** [marjoleinbruijning/trackdem#5]
Hi Marjolein,

I am trying to run the code to sequence my movies, but after the function is called, nothing happens.
I stick to basic paths and even if I state them explicitly, still I get no output, except for: "createImageSec v1.4"
I don't know how to troubleshoot this, do you have any idea?
I am running the code on a Windows 10 machine.

Cheers.

 createImageSeq(moviepath = "Movies", imagepath = "ImageSequences", fps = 25, nsec=3,
                ext = "MP4", libavpath = 'C:/Users/libav/usr/bin/avconv.exe', exiftoolpath = 'exiftool.exe',
                pythonpath = 'C:/Python27/python.exe', verbose = T)
createImageSec v1.4

**Comment by marjoleinbruijning** [comment]
Thanks for your question. I just uploaded a new createImageSeq() function to Github, that enables the creation of a log file (by setting logfile=TRUE; file will be saved in the working directory). Could you re-install trackdem from Github, run the function again, and paste the output of the log file?

Cheers, Marjolein

**Comment by PatWright** [comment]
Hi,
I think I'm having a similar issue where I nothing happens when I run the function. I've tried a combination of paths and settings that should work but the only message I get is 127.
Thanks,
Patrick

 createImageSeq(imagepath='Image_test', moviepath='Test',
               fps=5, nsec=2, ext="mp4",
                libavpath='~/libav/usr/bin/avconv.exe',
               exiftoolpath='~/Exif/exiftool.exe',
                pythonpath='~/python.exe',verbose = TRUE, logfile  = TRUE)
[1] 127

**Comment by marjoleinbruijning** [comment]
Dear Patrick,

I am currently on maternity leave and will look into your question when I
start work again in 3 to 4 weeks time.

Apologies,

Marjolein

**Comment by marjoleinbruijning** [comment]
Hi Patrick,

Could you please paste the output of the log file here, so that I can hopefully see what the issue is?

Cheers, Marjolein
