### ISSUE TITLE
mergeTracks | non numeric Matrix extent

### ISSUE THREAD

**Issue by haasdavid** [marjoleinbruijning/trackdem#8]
Dear Trackdem-Team,

I want to merge 9 Tracks of a larger dataset.
`records <- mergeTracks(records1, records2)` 
results in

> error in matrix(NA, ncol = ncol(mat1), nrow = nrow(m2)) : 
  non numeric matrix-extrent

If I use 
`records <- mergeTracks(records1, records2, L = 50, R = 10, weight = c(1,1,1))` 
instead it promts:

> Error in mergeTracks(records1, records2, L = 50, R = 10, weight = c(1,  : 
>   unused argument (R = 10)

Are theses known issues? I am using your package for the first time and don't really know, for what to look out here. 

Looking forward to your help.
Thank you and best regards,
David

**Comment by marjoleinbruijning** [comment]
Hi David,

Thanks for your question. I haven't seen the first error before. How many
identified particles are there in record1 and records2? (look at
summary(records1))

As for your second question, the function mergeTracks() doesn't have the
argument R, so try to delete this from your code.

Best, Marjolein

Op zo 25 apr. 2021 om 20:40 schreef haasdavid ***@***.***>:

**Comment by haasdavid** [comment]
Good Morning Marjolein,

thank you for your real quick response. Question two is solved. Many thanks!

For question one I provide you with more information in the following. If needed, I can provide you with 100 frames or more testdata:

- [https://1drv.ms/u/s!AlJI76ZyXH_Xg6UHnZc8buc5pNnrsw?e=E0Kx9L](url) (100 Frames, onedrive)

- Does `mergeTracks()` work with more than 2 TrDm?

- Eventhough I only use 50 images per set, they always go beyong 2 GB in Size (300 kb per picture; 1920 * 1080).

I use the following code (exerpt: I plan to merge 500+ images) on windows 10:

`summary(records1)`
> error in stats::kmeans(dist, 2) : 
>   more cluster centers than distinct data points.

` summary(records2)`
>  Summary of Linked particles: 
> > 	 Total of 6 Identified particles.
> > 	 Particles have a total area  of 0.0541 %
> > 	 Minimum presence is set at 1 frames 

```
setwd("")
require(trackdem)
require(shiny)

#images 1-50
allFullImages1 <- loadImages (dirPictures= ""
                             ,nImages = 1:50)
stillBack1 <- createBackground(allFullImages1, method = "mean")
allImages1 <- subtractBackground(bg = stillBack1)
partIden1 <- identifyParticles(sbg = allImages1,threshold = 0.02,
                              select = "light",
                              pixelRange = c(25,500),
                              autoThres = FALSE)
records1 <- trackParticles(partIden1, L = 50, R = 10, weight = c(1,1,1))
rm(list = c("allFullImages1", "stillBack1", "allImages1",
            "partIden1"))
gc()

#images 51-100

allFullImages2 <- loadImages (dirPictures= ""
                             ,nImages = 51:100)
stillBack2 <- createBackground(allFullImages2, method = "mean")
allImages2 <- subtractBackground(bg = stillBack2)
partIden2 <- identifyParticles(sbg = allImages2,threshold = 0.02,
                              select = "light",
                              pixelRange = c(25,500),
                              autoThres = FALSE)
records2 <- trackParticles(partIden2, L = 50, R = 10, weight = c(1,1,1))

## Merge tracked objects
records <- mergeTracks(records1, records2)
plot(records,colorimages=allFullImages2,type="trajectories")
````
And recieve the following error:
> records <- mergeTracks(records1, records2)
error in matrix(NA, ncol = ncol(mat1), nrow = nrow(m2)) : 
  non numeric matrix-extent
  
 Information on my R-Version:

> platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          4                           
minor          0.5                         
year           2021                        
month          03                          
day            31                          
svn rev        80133                       
language       R                           
version.string R version 4.0.5 (2021-03-31)
nickname       Shake and Throw 

Thank you for your support and this overall awesome package!

Best Regards,
David

**Comment by marjoleinbruijning** [comment]
There might be no or little particles in one or more frames. What does
dim(records1$trackRecord) give? And
apply(records1$trackRecord[,,1],2,function(X) sum(!is.na(X))) ?

Op ma 26 apr. 2021 om 11:49 schreef haasdavid ***@***.***>:

**Comment by haasdavid** [comment]
These commands return the following:
There are particles visible starting with frame one. I attatched the first frame to this entry. From what I can say the selected pixel range should be finde too: pixelRange = c(25,500)

> dim(records1$trackRecord)
[1]  6 50  2
> apply(records1$trackRecord[,,1],2,function(X) sum(!is.na(X)))
 [1] 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6

![image-00001](https://user-images.githubusercontent.com/83040873/116066327-39c66b00-a688-11eb-8e1b-c7b04539fbaa.png)

**Comment by marjoleinbruijning** [comment]
Hi David,

There was indeed a bug in the mergeTracks() function that could appear when
working with low numbers of particles. Should be solved now! Please install
the latest trackdem version from Github (I will soon upload it to CRAN as
well), and let me know if it solved your problem.

Best, Marjolein

Op ma 26 apr. 2021 om 12:11 schreef haasdavid ***@***.***>:

**Comment by haasdavid** [comment]
Hi Marjolein,

will do that right after work today. I am looking forward to try out the new version. Thank you very much for getting back on this matter so quickly.

Best regards,
David

**Comment by haasdavid** [comment]
Hi Marjolein,

could not stand the wait and snuck out. I had to try it.

`mergeTracks()` works fine now. Thank you so much! You kind of saved my master thesis ;-)
I was able to merge 9 subsets (one after another) now.

However, when I try to look at the individual summaries of e.g. `summary(records1)` I still recieve the following error
> error in stats::kmeans(dist, 2) : 
>   more cluster centers than distinct data points.

Could there be another issue in `identifyparticles`?

When I look at the summary of my merged subsets, it works just fine,

Best regards,
David

**Comment by marjoleinbruijning** [comment]
This is because the function attempts to find an automated threshold. This
assumes that there are multiple identified particles. From the error, it
seems that in this instance there was only one. I will update the package
to prevent this bug from occurring. You can avoid this by manually setting
the threshold (e.g. summary(records,incThres=1); see function description
for more info).

Best, Marjolein

Op ma 26 apr. 2021 om 14:21 schreef haasdavid ***@***.***>:
